/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as Top100RouteImport } from './routes/top-100'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RisingRouteImport } from './routes/rising'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewEntriesRouteImport } from './routes/new-entries'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilmsSlugRouteImport } from './routes/films.$slug'

const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const Top100Route = Top100RouteImport.update({
  id: '/top-100',
  path: '/top-100',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RisingRoute = RisingRouteImport.update({
  id: '/rising',
  path: '/rising',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewEntriesRoute = NewEntriesRouteImport.update({
  id: '/new-entries',
  path: '/new-entries',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsSlugRoute = FilmsSlugRouteImport.update({
  id: '/films/$slug',
  path: '/films/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/compare': typeof CompareRoute
  '/genres': typeof GenresRoute
  '/methodology': typeof MethodologyRoute
  '/new-entries': typeof NewEntriesRoute
  '/privacy': typeof PrivacyRoute
  '/rising': typeof RisingRoute
  '/terms': typeof TermsRoute
  '/top-100': typeof Top100Route
  '/trending': typeof TrendingRoute
  '/films/$slug': typeof FilmsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/compare': typeof CompareRoute
  '/genres': typeof GenresRoute
  '/methodology': typeof MethodologyRoute
  '/new-entries': typeof NewEntriesRoute
  '/privacy': typeof PrivacyRoute
  '/rising': typeof RisingRoute
  '/terms': typeof TermsRoute
  '/top-100': typeof Top100Route
  '/trending': typeof TrendingRoute
  '/films/$slug': typeof FilmsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/compare': typeof CompareRoute
  '/genres': typeof GenresRoute
  '/methodology': typeof MethodologyRoute
  '/new-entries': typeof NewEntriesRoute
  '/privacy': typeof PrivacyRoute
  '/rising': typeof RisingRoute
  '/terms': typeof TermsRoute
  '/top-100': typeof Top100Route
  '/trending': typeof TrendingRoute
  '/films/$slug': typeof FilmsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calendar'
    | '/compare'
    | '/genres'
    | '/methodology'
    | '/new-entries'
    | '/privacy'
    | '/rising'
    | '/terms'
    | '/top-100'
    | '/trending'
    | '/films/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calendar'
    | '/compare'
    | '/genres'
    | '/methodology'
    | '/new-entries'
    | '/privacy'
    | '/rising'
    | '/terms'
    | '/top-100'
    | '/trending'
    | '/films/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calendar'
    | '/compare'
    | '/genres'
    | '/methodology'
    | '/new-entries'
    | '/privacy'
    | '/rising'
    | '/terms'
    | '/top-100'
    | '/trending'
    | '/films/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalendarRoute: typeof CalendarRoute
  CompareRoute: typeof CompareRoute
  GenresRoute: typeof GenresRoute
  MethodologyRoute: typeof MethodologyRoute
  NewEntriesRoute: typeof NewEntriesRoute
  PrivacyRoute: typeof PrivacyRoute
  RisingRoute: typeof RisingRoute
  TermsRoute: typeof TermsRoute
  Top100Route: typeof Top100Route
  TrendingRoute: typeof TrendingRoute
  FilmsSlugRoute: typeof FilmsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-100': {
      id: '/top-100'
      path: '/top-100'
      fullPath: '/top-100'
      preLoaderRoute: typeof Top100RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rising': {
      id: '/rising'
      path: '/rising'
      fullPath: '/rising'
      preLoaderRoute: typeof RisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-entries': {
      id: '/new-entries'
      path: '/new-entries'
      fullPath: '/new-entries'
      preLoaderRoute: typeof NewEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$slug': {
      id: '/films/$slug'
      path: '/films/$slug'
      fullPath: '/films/$slug'
      preLoaderRoute: typeof FilmsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalendarRoute: CalendarRoute,
  CompareRoute: CompareRoute,
  GenresRoute: GenresRoute,
  MethodologyRoute: MethodologyRoute,
  NewEntriesRoute: NewEntriesRoute,
  PrivacyRoute: PrivacyRoute,
  RisingRoute: RisingRoute,
  TermsRoute: TermsRoute,
  Top100Route: Top100Route,
  TrendingRoute: TrendingRoute,
  FilmsSlugRoute: FilmsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
